package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"time"

	_ "media-service/docs" // This will be generated by swag init
	"media-service/internal/api"
	"media-service/internal/gc"
	"media-service/internal/processing"
	"media-service/internal/storage/minio"
	"media-service/internal/storage/postgres"
	"media-service/internal/upload"
	"media-service/internal/worker"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
	minioClient "github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// @title Media Service Control Plane API
// @version 1.0
// @description Internal platform service for handling blob lifecycles, multipart uploads, and processing orchestration.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /
func main() {
	ctx := context.Background()

	// 1. Initialize PostgreSQL
	dbUrl := os.Getenv("DATABASE_URL")
	if dbUrl == "" {
		dbUrl = "postgres://postgres:password@localhost:5432/media?sslmode=disable"
	}
	pool, err := pgxpool.New(ctx, dbUrl)
	if err != nil {
		log.Fatalf("Failed to connect to postgres: %v", err)
	}
	defer pool.Close()
	metadataRepo := postgres.NewMetadataRepo(pool)

	// 2. Initialize MinIO
	endpoint := os.Getenv("MINIO_ENDPOINT")
	if endpoint == "" {
		endpoint = "localhost:9010"
	}
	minioUser := os.Getenv("MINIO_ROOT_USER")
	if minioUser == "" {
		minioUser = "minioadmin"
	}
	minioPass := os.Getenv("MINIO_ROOT_PASSWORD")
	if minioPass == "" {
		minioPass = "minioadmin"
	}

	mc, err := minioClient.New(endpoint, &minioClient.Options{
		Creds:  credentials.NewStaticV4(minioUser, minioPass, ""),
		Secure: false,
	})
	if err != nil {
		log.Fatalf("Failed to initialize minio client: %v", err)
	}
	blobStorage := minio.NewBlobStorage(mc, "media-blobs")

	// 3. Setup Async Hashing Worker
	hashChan := make(chan uuid.UUID, 100) // Buffer 100 jobs
	hashWorker := worker.NewHashWorker(metadataRepo, blobStorage, hashChan)
	go hashWorker.Start(ctx)

	// 4. Setup GC Worker
	// In production, intervals should be longer (e.g. 1 hour interval, 24 hours grace)
	// Using short times here for demonstration
	gcWorker := gc.NewWorker(metadataRepo, blobStorage, 10*time.Minute, 24*time.Hour)
	go gcWorker.Start(ctx)

	// 5. Setup Processing Service (Skeleton)
	processingSvc := processing.NewService(metadataRepo)
	_ = processingSvc // Ready to be injected into future handlers or event listeners

	// 6. Setup Upload Service & API
	uploadSvc := upload.NewService(metadataRepo, blobStorage, hashChan)

	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	h := api.NewHandlers(uploadSvc)
	apiRouter := api.NewRouter(h)

	r.Mount("/", apiRouter)

	// Swagger documentation endpoint
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"),
	))

	log.Println("Media Service starting on :8080...")
	log.Println("Swagger docs available at http://localhost:8080/swagger/index.html")
	if err := http.ListenAndServe(":8080", r); err != nil {
		log.Fatalf("Server failed: %v", err)
	}
}
