// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/blobs/{blobId}": {
            "delete": {
                "description": "Synchronously deletes a blob from S3 and its metadata from the database. Typically used for administrative actions, DMCA, or GDPR purges.",
                "tags": [
                    "blobs"
                ],
                "summary": "Force deletes a blob",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Blob ID",
                        "name": "blobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Accepted / Deleted"
                    }
                }
            }
        },
        "/blobs/{blobId}/download-url": {
            "get": {
                "description": "Returns a direct S3 presigned URL for downloading the blob (Control Plane approach)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "blobs"
                ],
                "summary": "Gets a presigned download URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Blob ID",
                        "name": "blobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"url\": \"https://...\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/uploads/init": {
            "post": {
                "description": "Creates an S3 multipart upload session and returns presigned URLs for direct client-to-S3 upload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Initializes a multipart upload",
                "parameters": [
                    {
                        "description": "Upload Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.InitUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.InitUploadResponse"
                        }
                    }
                }
            }
        },
        "/uploads/{sessionId}": {
            "get": {
                "description": "Returns the current status of the upload session and the resulting blobId if completed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Gets the status of an upload session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.UploadSessionResponse"
                        }
                    }
                }
            }
        },
        "/uploads/{sessionId}/complete": {
            "post": {
                "description": "Validates parts, completes the S3 multipart upload, and triggers the async hashing pipeline",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "Completes a multipart upload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Uploaded Parts with ETags",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.CompleteUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted - Processing started"
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api.CompleteUploadRequest": {
            "type": "object",
            "properties": {
                "parts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.UploadPartReq"
                    }
                }
            }
        },
        "internal_api.InitUploadRequest": {
            "type": "object",
            "properties": {
                "expectedSize": {
                    "type": "integer"
                },
                "mimeType": {
                    "type": "string"
                },
                "partsCount": {
                    "type": "integer"
                }
            }
        },
        "internal_api.InitUploadResponse": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "type": "string"
                },
                "parts": {
                    "description": "map of PartNumber to Presigned URL",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "sessionId": {
                    "type": "string"
                }
            }
        },
        "internal_api.UploadPartReq": {
            "type": "object",
            "properties": {
                "etag": {
                    "type": "string"
                },
                "partNumber": {
                    "type": "integer"
                }
            }
        },
        "internal_api.UploadSessionResponse": {
            "type": "object",
            "properties": {
                "blobId": {
                    "type": "string"
                },
                "sessionId": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/media-service_internal_domain.SessionStatus"
                }
            }
        },
        "media-service_internal_domain.SessionStatus": {
            "type": "string",
            "enum": [
                "UPLOADING",
                "FINALIZING",
                "COMPLETED",
                "ABANDONED"
            ],
            "x-enum-varnames": [
                "SessionUploading",
                "SessionFinalizing",
                "SessionCompleted",
                "SessionAbandoned"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Media Service Control Plane API",
	Description:      "Internal platform service for handling blob lifecycles, multipart uploads, and processing orchestration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
